name: e2e

on:
  pull_request:
    branches: [ '**' ]

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Playwright E2E (@mcpay/app)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/app
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers and OS deps
        run: pnpm run e2e:install

      # Optional: build once; globalSetup also builds, but this speeds up and fails fast
      - name: Build app
        run: pnpm run build
        env:
          NODE_ENV: test

      - name: Run E2E tests
        run: pnpm run e2e:test --reporter=line,html
        env:
          CI: 'true'

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/app/playwright-report
          if-no-files-found: warn

      - name: Upload per-test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          path: |
            apps/app/tests/e2e/artifacts
            apps/app/test-results/per-test-logs
          if-no-files-found: warn


